nelmio_cors:
    defaults:
        allow_credentials: true
        origin_regex: true
        allow_origin: ['https://bookstore-webapp-ruby.vercel.app']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['https://bookstore-webapp-ruby.vercel.app',  'http://localhost:5173']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: ['Link']
            max_age: 3600
